<?php
if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'group_about_section',
        'title' => 'About Section',
        'fields' => array(
            // array(
            //     'key' => 'field_about_title',
            //     'label' => 'Page Title',
            //     'name' => 'about_page_title',
            //     'type' => 'text',
            //     'instructions' => '',
            //     'required' => 1,
            //     'conditional_logic' => false,
            //     'wrapper' => array(
            //         'width' => '',
            //         'class' => '',
            //         'id' => '',
            //     ),
            //     'placeholder' => '',
            // ),
            array(
                'key' => 'field_about_titlee',
                'label' => 'Title',
                'name' => 'about_title',
                'type' => 'text',
                'required' => 1,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'rows' => 5,
                'default_value' => '',
                'new_lines' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_about_description',
                'label' => 'Description',
                'name' => 'about_description',
                'type' => 'textarea',
                'instructions' => 'Isi paragraf pendahuluan tentang sanggar.',
                'required' => 1,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'rows' => 5,
                'default_value' => '',
                'new_lines' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_leader_title',
                'label' => 'Leader Section Title',
                'name' => 'leader_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Pimpinan Sanggar Obor Sakti',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_leader_photo',
                'label' => 'Leader Photo',
                'name' => 'leader_photo',
                'type' => 'image',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
            ),
            array(
                'key' => 'field_leader_description',
                'label' => 'Leader Description',
                'name' => 'leader_description',
                'type' => 'textarea',
                'instructions' => 'Deskripsi singkat pimpinan sanggar.',
                'required' => 1,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'rows' => 5,
                'default_value' => '',
                'new_lines' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_program_classes',
                'label' => 'Program Classes',
                'name' => 'program_classes',
                'type' => 'repeater',
                'instructions' => 'Isi daftar kelas untuk slider. Setiap item adalah satu slide.',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_class_title',
                'min' => 1,
                'layout' => 'block',
                'button_label' => 'Tambah Kelas',
                'sub_fields' => array(
                    array(
                        'key' => 'field_class_title',
                        'label' => 'Class Title',
                        'name' => 'class_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => false,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_class_content_type',
                        'label' => 'Content Type',
                        'name' => 'class_content_type',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => false,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'list' => 'List',
                            'paragraph' => 'Paragraph',
                        ),
                        'default_value' => 'list',
                        'layout' => 'vertical',
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'allow_null' => 0,
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'field_class_items',
                        'label' => 'Class Items',
                        'name' => 'class_items',
                        'type' => 'repeater',
                        'instructions' => 'Isi poin-poin kelas, jika content type "List"',
                        'required' => false,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_class_content_type',
                                    'operator' => '==',
                                    'value' => 'list',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'min' => 1,
                        'layout' => 'table',
                        'button_label' => 'Tambah Poin',
                        'collapsed' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_class_item',
                                'label' => 'Item',
                                'name' => 'item',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_class_paragraph',
                        'label' => 'Class Paragraph',
                        'name' => 'class_paragraph',
                        'type' => 'textarea',
                        'instructions' => 'Isi deskripsi paragraf, jika content type "Paragraph"',
                        'required' => false,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_class_content_type',
                                    'operator' => '==',
                                    'value' => 'paragraph',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'rows' => 5,
                        'default_value' => '',
                        'new_lines' => '',
                        'placeholder' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'data-page',
                ),
            ),
        ),
        'menu_order' => 1,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => 'Field group untuk halaman About dengan slider kelas dan foto pimpinan',
    ));

endif;
