<?php
if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
        'key' => 'group_data_page',
        'title' => 'Home Section',
        'fields' => array(
            array(
                'key' => 'field_home',
                'label' => 'Home',
                'name' => 'home',
                'type' => 'group',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => false,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'acfe_group_modal_close' => 0,
                'acfe_group_modal_button' => '',
                'acfe_group_modal_size' => 'large',
                'sub_fields' => array(
                    array(
                        'key' => 'field_home_section_banner',
                        'label' => 'Section Banner',
                        'name' => 'section_banner',
                        'type' => 'repeater',
                        'instructions' => 'Add slides for banner slider',
                        'required' => false,
                        'conditional_logic' => false,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'min' => 0,
                        'layout' => 'block',
                        'button_label' => 'Add Slide',
                        'max' => 0,
                        'collapsed' => '',
                        'acfe_repeater_stylised_button' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_slide_title',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_slide_description',
                                'label' => 'Description',
                                'name' => 'description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'rows' => 3,
                                'default_value' => '',
                                'new_lines' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'acfe_textarea_code' => 0,
                            ),
                            array(
                                'key' => 'field_slide_image',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'min_width' => 0,
                                'min_height' => 0,
                                'min_size' => 0,
                                'max_width' => 0,
                                'max_height' => 0,
                                'max_size' => 0,
                                'mime_types' => '',
                                'uploader' => '',
                                'acfe_thumbnail' => 0,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_home_section_art_exploration',
                        'label' => 'Section Art Exploration',
                        'name' => 'section_art_exploration',
                        'type' => 'repeater',
                        'instructions' => 'Add images for art exploration slider',
                        'required' => false,
                        'conditional_logic' => false,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'min' => 0,
                        'layout' => 'block',
                        'button_label' => 'Add Slide',
                        'max' => 0,
                        'collapsed' => '',
                        'acfe_repeater_stylised_button' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_art_exploration_image',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'min_width' => 0,
                                'min_height' => 0,
                                'min_size' => 0,
                                'max_width' => 0,
                                'max_height' => 0,
                                'max_size' => 0,
                                'mime_types' => '',
                                'uploader' => '',
                                'acfe_thumbnail' => 0,
                            ),
                            array(
                                'key' => 'field_art_exploration_alt',
                                'label' => 'Alt Text',
                                'name' => 'alt',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_home_section_about',
                        'label' => 'Section About',
                        'name' => 'section_about',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => false,
                        'conditional_logic' => false,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_seamless_style' => 0,
                        'acfe_group_modal' => 0,
                        'acfe_group_modal_close' => 0,
                        'acfe_group_modal_button' => '',
                        'acfe_group_modal_size' => 'large',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_about_background_image',
                                'label' => 'Background Image',
                                'name' => 'background_image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'min_width' => 0,
                                'min_height' => 0,
                                'min_size' => 0,
                                'max_width' => 0,
                                'max_height' => 0,
                                'max_size' => 0,
                                'mime_types' => '',
                                'uploader' => '',
                                'acfe_thumbnail' => 0,
                            ),
                            array(
                                'key' => 'field_about_title',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 'About Us',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_about_text',
                                'label' => 'Text',
                                'name' => 'text',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'rows' => 6,
                                'default_value' => '',
                                'new_lines' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'acfe_textarea_code' => 0,
                            ),
                            array(
                                'key' => 'field_about_button_text',
                                'label' => 'Button Text',
                                'name' => 'button_text',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 'See Now',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_home_section_cta',
                        'label' => 'Section CTA',
                        'name' => 'section_cta',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => false,
                        'conditional_logic' => false,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'acfe_seamless_style' => 0,
                        'acfe_group_modal' => 0,
                        'acfe_group_modal_close' => 0,
                        'acfe_group_modal_button' => '',
                        'acfe_group_modal_size' => 'large',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_cta_text',
                                'label' => 'Text',
                                'name' => 'text',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => true,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'rows' => 3,
                                'default_value' => 'Wujudkan Potensi
        Kreativitasmu Tanpa Batas!',
                                'new_lines' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'acfe_textarea_code' => 0,
                            ),
                            array(
                                'key' => 'field_cta_button_text',
                                'label' => 'Button Text',
                                'name' => 'button_text',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => true,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 'Gabung Sekarang',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_cta_background_color',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'type' => 'color_picker',
                                'instructions' => '',
                                'required' => false,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '#FA9136',
                            ),
                            array(
                                'key' => 'field_cta_button_color',
                                'label' => 'Button Color',
                                'name' => 'button_color',
                                'type' => 'color_picker',
                                'instructions' => '',
                                'required' => false,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '#F97316',
                            ),
                            array(
                                'key' => 'field_6802ba43efca8',
                                'label' => 'Button Url',
                                'name' => 'button_url',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_home_section_testimonials',
                        'label' => 'Section Testimonials',
                        'name' => 'section_testimonials',
                        'type' => 'repeater',
                        'instructions' => 'Add client testimonials',
                        'required' => false,
                        'conditional_logic' => false,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'min' => 0,
                        'layout' => 'block',
                        'button_label' => 'Add Testimonial',
                        'max' => 0,
                        'collapsed' => '',
                        'acfe_repeater_stylised_button' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_testimonial_name',
                                'label' => 'Name',
                                'name' => 'name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_testimonial_position',
                                'label' => 'Position',
                                'name' => 'position',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_testimonial_photo',
                                'label' => 'Photo',
                                'name' => 'photo',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                                'min_width' => 0,
                                'min_height' => 0,
                                'min_size' => 0,
                                'max_width' => 0,
                                'max_height' => 0,
                                'max_size' => 0,
                                'mime_types' => '',
                                'uploader' => '',
                                'acfe_thumbnail' => 0,
                            ),
                            array(
                                'key' => 'field_testimonial_border_color',
                                'label' => 'Border Color (Tailwind CSS Class)',
                                'name' => 'border_color',
                                'type' => 'text',
                                'instructions' => 'Example: border-blue-500, border-green-500',
                                'required' => 0,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_testimonial_text',
                                'label' => 'Testimonial Text',
                                'name' => 'text',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => false,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'rows' => 4,
                                'default_value' => '',
                                'new_lines' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'acfe_textarea_code' => 0,
                            ),
                        ),
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'data-page',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ));

endif;
